name: Verify Quality

on:
  push:
    branches-ignore: ["prod"]

permissions:
  contents: read

jobs:
  verify-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Node / npm
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm clean-install

      - name: Lint with eslint
        run: npx eslint core/

      - name: Format with prettier
        run: npx prettier --check core/

      - name: Ensure package build passes
        run: npm run build

      - name: Ensure storybook build passes
        run: npm run build-storybook
